#!/usr/bin/env bash

# If you are trying to install these tools and run them on a system that isn't
# Linux/Unix, these instructions will likely not work for you.

# Normally, all that would be required to install remind would be to use the
# already packaged version provided by your chosen Linux distribution.  On
# Debian/Ubuntu, this is usually done by typing:

# sudo apt-get --yes install remind

# The current version of remind does not allow the desired language to be
# specified at the command-line, so, if you want to make calendars for a
# language other than your native locale, you will be required to rebuild
# remind from source.  One way of doing this is to execute the following:

sudo apt-get --yes install build-essential

remind_version='remind-03.03.01'
remind_gpg_key_id='738E4D954052902C147D07B2685A5A5E511D30E2'
temp_location='tmp'
target_location='/usr/local/bin'

# Prepare stuff
mkdir --parents ${temp_location}
pushd ${temp_location}

# Fetch stuff
location=https://dianne.skoll.ca/projects/remind/download
wget ${location}/${remind_version}.tar.gz.sig
wget ${location}/${remind_version}.tar.gz
gpg --recv-key ${remind_gpg_key_id}
gpg --export --armor --no-emit-version --no-comment ${remind_gpg_key_id} >\
    ${remind_gpg_key_id}.gpg.pub.txt

# Verify stuff
gpg --verify ${remind_version}.tar.gz.sig ${remind_version}.tar.gz
read

# Extract stuff
tar --extract --verbose --gzip --file ${remind_version}.tar.gz

# Build French stuff
pushd ${remind_version}
# XXX FIXME XXX hack FOrd() in src/funcs.c to force the strings to be French
make "LANGDEF=-DLANG=FRENCH"
sudo cp src/remind ${target_location}/remind.fr
sudo cp src/rem2ps ${target_location}/rem2ps.fr

# Build English stuff
make clean
make "LANGDEF=-DLANG=ENGLISH"
sudo cp src/remind ${target_location}/remind.en
sudo cp src/rem2ps ${target_location}/rem2ps.en
popd

# Clean up stuff
popd
# rm --recursive --force ${temp_location}

# Naming the newly-built binaries in this manner works with the provided
# makefile to call the appropriate remind and rem2ps backend binaries
# depending on the desired language.

# Debian 7.x ships with remind 03.01.12 and Ubuntu 13.10 ships with remind
# 03.01.13.  Since there may be subtle differences with the way things look
# from version to version, if you are concerned about making both an English
# and French calendar that look the same, you should probably make sure to
# build the same version of remind for all the languages for which you wish to
# make calendars.

# If you wish to provide support for other languages, you should build
# whichever binaries are appropriate for your needs using the instructions
# above, and then add additional entries wherever you see the "babel()" remind
# function being used.

# To perform some other operations related to generating or working with these
# calendars, you will probably also want to install some additional tools by
# typing:

# sudo apt-get --yes install ghostscript psutils pdftk inkscape libreoffice
