#!/usr/bin/env bash

# If you are trying to install these tools and run them on a system that isn't
# Linux/Unix, these instructions will likely not work for you.

# Normally, all that would be required to install remind would be to use the
# already packaged version provided by your chosen Linux distribution.  On
# Debian/Ubuntu, this is usually done by typing:

#  sudo apt-get install remind

# The current version of remind does not allow the desired language to be
# specified at the command-line, so, if you want to make calendars for a
# language other than your native locale, you will be required to rebuild
# remind from source.  One way of doing this is to execute the following:

  sudo apt-get install build-essential

  mkdir --parents tmp
  cd tmp

  REMIND_VERSION='remind-03.01.14'
  wget http://www.roaringpenguin.com/files/download/${REMIND_VERSION}.tar.gz.sig
  wget http://www.roaringpenguin.com/files/download/${REMIND_VERSION}.tar.gz
  gpg --recv-key 126F42E0
  gpg --export --armor --no-emit-version --no-comment 126F42E0 >\
    126F42E0.gpg.pub.txt
  gpg --verify ${REMIND_VERSION}.tar.gz.sig ${REMIND_VERSION}.tar.gz

  tar --extract --verbose --gzip --file ${REMIND_VERSION}.tar.gz
  cd ${REMIND_VERSION}
  make "LANGDEF=-DLANG=FRENCH"
  sudo cp src/remind /usr/local/bin/remind.fr
  sudo cp src/rem2ps /usr/local/bin/rem2ps.fr

  make clean
  make "LANGDEF=-DLANG=ENGLISH"
  sudo cp src/remind /usr/local/bin/remind.en
  sudo cp src/rem2ps /usr/local/bin/rem2ps.en

# Naming the newly-built binaries in this manner works with the provided
# makefile to call the appropriate remind and rem2ps backend binaries
# depending on the desired language.

# Debian 7.5 ships with remind 03.01.12 and Ubuntu 13.10 ships with remind
# 03.01.13.  Since there may be subtle differences with the way things look
# from version to version, if you are concerned about making both an English
# and French calendar that look the same, you should probably make sure to
# build the same version of remind for all the languages for which you wish to
# make calendars.

# If you wish to provide support for other languages, you should build
# whichever binaries are appropriate for your needs using the instructions
# above, and then add additional entries wherever you see the "babel()" remind
# function being used.

# To perform some other operations related to generating or working with these
# calendars, you will probably also want to install some additional tools by
# typing:

  sudo apt-get install ghostscript psutils pdftk inkscape libreoffice
